services:
  front:
    build:
      context: ./QA-front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - back  
  back:
    build:
      context: ./QA-back
      dockerfile: Dockerfile 
    ports:
      - 8000:8000  
    depends_on:
      - db  
  db:
    # build:
    #   context: ./BDD
    #   dockerfile: Dockerfile
    image: mariadb:11
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./BDD/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
volumes:
  db_data:
    external: true
