FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copier et construire l'application
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /build

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as runtime
WORKDIR /app
COPY --from=build /build /app
ENTRYPOINT [ "dotnet", "QA-back.dll" ]
