services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  front:
    container_name: front
    build:
      context: ../QA-front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL= http://back
#    volumes:
#      - ./certificates:/certificates:ro
    depends_on:
      - back 
    networks:
      - my-network
  back:
    container_name: back
    build:
      context: ../QA-back
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=server=$MYSQL_DATABASE;port=3306;database=automatebdd;user=$MYSQL_USER;password=$MYSQL_PASSWORD;
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - my-network
  db:
    container_name: automatebdd
    image: mariadb:11
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ../BDD/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
