# Utilisation de l'image officielle MySQL
FROM mysql:latest

# Copier les scripts SQL vers le répertoire du conteneur
COPY init.sql /docker-entrypoint-initdb.d/init.sql

# Exposer le port par défaut de MySQL
EXPOSE 3306

# Définition des variables d'environnement
ENV MYSQL_ROOT_PASSWORD=mysecretpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Commande de démarrage du conteneur
CMD ["mysqld"]